### ISSUE TITLE
Missing files on NPM packages

### ISSUE THREAD

**Issue by damianpumar** [glippi/kataclism#12]
I installed Kataclism from npm following your readme file, but when I try to create a new kata, I get this message.
Maybe you need to add missing files on your npm package.
![Screen Shot](https://user-images.githubusercontent.com/7398909/76679339-fa51d200-65df-11ea-8aea-c456e73fcc3b.png)

Hope it's helpful.

**Comment by glippi** [comment]
Thank you very much @damianpumar!

I think that I found and fix the problem, could you try to use the package now?

The latest version is the 1.1.10.

Have a nice week end ;)

**Comment by damianpumar** [comment]
You are welcome!
Works correctly @glippi 

Thanks! :blush:

**Comment by glippi** [comment]
Great!
I will close this issue.

Thanks for your help :)
